from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class ConfigSource(Protocol):
    async def read_text(self, relpath: str) -> str: ...
    async def write_text(self, relpath: str, content: str) -> None: ...
    async def list_dir(self, relpath: str) -> list[str]: ...
    async def exists(self, relpath: str) -> bool: ...
    async def run(self, cmd: list[str]) -> tuple[int, str, str]: ...
    async def close(self) -> None: ...
